### ISSUE TITLE
Steps to use with Arduino Esp8266 board

### ISSUE THREAD

**Issue by waghekapil** [medovarsky/BearSSL#1]
Hello,

Thanks for the library.

Can you please guide me to use this library in Arduino SDK for ESP8266 board. I want to use it for AWS IoT secure MQTT connection.

AWS IoT supports TLS1.2.

**Comment by medovarsky** [comment]
Hi,

Please find the author in library.json. The library itself is made by a different author, and this file is the only contribution I have made in order to make it visible to Platformio audience.
